# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Coopdevs
email: info@coopdevs.org
description: > # this means to ignore newlines until "baseurl:"
  TICs para el desarrollo de la economia social
  ITC for the development of the social economy
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://coopdevs.org" # the base hostname & protocol for your site
twitter_username: coopdevs
github_username:  coopdevs

# Build settings
markdown: kramdown

# this will be overwritten by github
github:
  url: "http://0.0.0.0:4000"
